### ISSUE TITLE
Wassertemperatur Soll automatisch erhöht 

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#10]
Die Soll Temperatur wird um 0,5°C erhöht.
Ursache scheint zu sein wenn die LWP nicht erreichbar ist

Siehe Log
![image](https://user-images.githubusercontent.com/34193151/100538446-2ecdf280-3230-11eb-8c8d-664fb7990dbe.png)

Und Tabelleneintrag
![image](https://user-images.githubusercontent.com/34193151/100538458-460ce000-3230-11eb-8536-97b7e8cf3ad6.png)

Hängt vielleicht aber auch mit dem luxtronik2.0.parameters.temperature_hot_water_target Parameter zusammen
Beide unterscheiden sich bei mir
![image](https://user-images.githubusercontent.com/34193151/100538551-bddb0a80-3230-11eb-8b18-7dda9427a6d1.png)

**Comment by TbsJah** [comment]
Das Ändern des Parameters luxtronik2.0.parameters.warmwater_temperature ändert nur den Wert WP Deckung bei der Luxtronik
Der Parameter luxtronik2.0.parameters.temperature_hot_water_target bildet den Wert Wunschwert ab.

Dieser wird nicht geändert. Daher das aktualisieren der Werte wenn die WP nicht erreichbar ist

**Comment by UncleSamSwiss** [comment]
Sorry, ich verstehe nicht ganz, was jetzt falsch ist und was richtig wäre?

**Comment by TbsJah** [comment]
Aktuell ist es so, dass der Adapter wenn er die LWP nicht erreicht den Parameter luxtronik2.0.parameters.warmwater_temperature um 0,5°C erhöht (bis er den Wert von temperature_hot_water_target erreciht hat) .
Das liegt daran dass bei Änderung des H2O Soll Wert (über den Adapter) der Wert WP Deckung in der Luxtronik Steuerung geändert wird und nicht der Wert Wunschwert Deckung --> luxtronik2.0.parameters.temperature_hot_water_target

Über den FHEM Adapter oder dem Android Tool LuxProbe besteht das Problem nicht.
Bei beiden wird zwar auch "nur" der Wert WP Deckung aktualisiert, aber der Wert nicht automatisch um 0,5°C erhöht.

Ich denke ein Workaround könnte sein am Regler selber eine niedrigere Temperatur einzustellen und dann über den Adapter den Wert zu Ändern. Wobei ich dann nicht weiß ob dann nach unten reguliert werden würde (automatisch wieder mit 0,5°C immer wenn der Adapter die LWP nicht erreicht)


Lange Rede kurzer Sinn. 
Wenn Wunschwert und WP Deckung am Regler unterschiedlich sind (das passiert wenn von außerhalb der Wert eingestellt wird) dann wird jedes Mal wenn die WP nicht erreichbar ist (busy Meldung) der Wert zum Wunschwert Regler um 0,5°C angepasst.

**Comment by TbsJah** [comment]
Ursache gefunden - Ursache wenn Wunschwert unterschiedlich zu WP Deckung
![image](https://user-images.githubusercontent.com/34193151/100854490-5b307b80-3489-11eb-9c17-57280f9367b6.png)

**Comment by UncleSamSwiss** [comment]
Bedeutet das, dass ich etwas ändern muss im Code oder ist das so in Ordnung?

**Comment by TbsJah** [comment]
Kann geschlossen werden
Lösung ist am Regler selber den Deckungswert niedriger zu stellen - Beispiel 20°C
