### ISSUE TITLE
"Mischkreis1" (MK1) Heizkurve fehlt 

### ISSUE THREAD

**Issue by BlackEdder0815** [UncleSamSwiss/ioBroker.luxtronik2#123]
Ich habe die Heizkurve für den MK1 nicht gefunden. Die Heizkurve für den Heizkreis ist vorhanden und kann man auch erfolgreich setzen (`heating_curve_end_point` und `heating_curve_parallel_offset`). Wäre es viel Aufwand, die zwei Werte für den Mischkreis MK1 auch hinzuzunehmen?
Danke und Grüße

**Comment by BlackEdder0815** [comment]
Nach Recherche müssten es diese Parameter sein:
14 - ID_Einst_HzMK1E_akt  <-- Endpunkt Heizkurve MK1
15 - ID_Einst_HzMK1ANH_akt <-- Anhebung Heizkurve MK1
16 - ID_Einst_HzMK1ABS_akt <-- Nachtabsenkung Heizkurve MK1

Ich habe in den sourcen leider noch nicht gefunden, wo die IDs hinterlegt sind, sonst hätte ich ein Pull-Request gemacht bzw. es ausprobiert.

**Comment by UncleSamSwiss** [comment]
Da dies in einer Library ist, die ich nur verwende, habe ich dort ein Issue erstellt:
https://github.com/coolchip/luxtronik2/issues/26

Wenn du selber Hand anglegen willst, kannst du gerne in der luxtronik2 Library die Daten anpassen:
Ich vermute es ist die Methode hier, aber selber habe ich damit noch nie etwas gemacht:
https://github.com/coolchip/luxtronik2/blob/298cfd44d0f5d9887a2ef38c0d7c0af8aa18e869/luxtronik.js#L213

**Comment by BlackEdder0815** [comment]
Das sieht gut aus, danke!
Basierend auf https://github.com/Bouni/Luxtronik-2/blob/master/documentation.md scheint es genau die Stelle zu sein. 
```
'heating_curve_end_point': (heatpumpVisibility[207] === 1) ? heatpumpParameters[11] / 10 : 'no', // #69
'heating_curve_parallel_offset': (heatpumpVisibility[207] === 1) ? heatpumpParameters[12] / 10 : 'no', // #70
```
entspricht genau den Werten (11;12) für die Heizkurzve des Primärkreises.

**Comment by UncleSamSwiss** [comment]
This should be fixed with the latest luxtronik2 module which is included in adapter version 0.4.0.
