### ISSUE TITLE
Empty Values heatSourceDefrostAirEnd / heatSourceDefrostAirEnd

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#158]
![image](https://user-images.githubusercontent.com/34193151/145029633-88f1ff7d-2b05-424d-9c8b-61c192b8fcd9.png)

**Comment by UncleSamSwiss** [comment]
This should be fixed with the latest luxtronik2 module which is included in adapter version 0.4.0.
If it isn't fixed, please reopen this issue.

**Comment by TbsJah** [comment]
@UncleSamSwiss do not know how to reopen the issue 
The issue isn't fix. There is now value for both

**Comment by UncleSamSwiss** [comment]
Looking at the code that generates these values, it seems that your heatpump is not reporting the values:

https://github.com/coolchip/luxtronik2/blob/ac120059de434b5f8cd7287fba6479565eb4adad/luxtronik.js#L237

https://github.com/coolchip/luxtronik2/blob/ac120059de434b5f8cd7287fba6479565eb4adad/luxtronik.js#L231

In both cases, `null` is reported when the corresponding `heatpumpVisibility` value is not set to `1`. This is directly coming from your heatpump.
