### ISSUE TITLE
Abschaltungen

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#3]
Bestehende DP werden nicht mit den neuen Werten aktualisiert
Es werden neue DP angelegt
![image](https://user-images.githubusercontent.com/34193151/99143488-26858d00-265e-11eb-97a6-31f2a5d8bdc7.png)

Bug oder Feature?
Evtl in Optionen Auswahl wie viele Einträge behalten werden sollen
Der Rest wird gelöscht

**Comment by UncleSamSwiss** [comment]
Ja, das ist aktuell sehr unschön, bis jetzt habe ich mich noch nicht darum gekümmert, wie ich die Daten sinnvoll darstellen soll.
Mein Gefühl sagt mir, dass Datenpunkte mit dem Zeitstempel sinnlos sind; wahrscheinlich sollte ich eher ein einzelner State mit JSON als Text haben, den man dann in der vis darstellen kann. Oder andere Vorschläge?

**Comment by Tuphal** [comment]
Sas Selbe ist auch beim Fehlerspeicher. Da wird auch nach Zeitstempel sortiert. Da der Zeitstempel aber den Tag zuerst hat, ist der Fehler vom 23.3. mitten drin:
![grafik](https://user-images.githubusercontent.com/42291781/112169453-7f5bc800-8bf2-11eb-863c-41b0bd8a4881.png)


Dadurch kann man die Fehler gar nicht per InfluxDB auslesen oder visualisieren.
