### ISSUE TITLE
Unknown data

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#45]
I had a total breakdown of my Raspberry the day before yesterday.
Yesterday I restored the backup. Since then I have been getting the messages shown. 

![image](https://user-images.githubusercontent.com/34193151/112106505-0d618f80-8bae-11eb-946d-8a2db25856f9.png)

**Comment by theend-dev** [comment]
I get the same messages after 4 days uptime. There was no crash involved.

![grafik](https://user-images.githubusercontent.com/82474042/114614582-03aae380-9ca5-11eb-86f4-c8626276781e.png)

**Comment by hb84** [comment]
I receive these warnings ever since I installed the adapter
![grafik](https://user-images.githubusercontent.com/82756881/115142293-4243f380-a041-11eb-8003-f6e8084b7ca2.png)
