### ISSUE TITLE
temperature_hot_water_target wird nicht nach Änderung aktualisert

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#5]
Nach Eingabe bei 
luxtronik2.0.parameters.warmwater_temperature wird der Wert bei luxtronik2.0.parameters.temperature_hot_water_target nicht aktualisiert

Werte werden jedoch korrekt von Regler übernommen

![image](https://user-images.githubusercontent.com/34193151/99143671-9e07ec00-265f-11eb-9a5e-ab0c49b419f9.png)

**Comment by UncleSamSwiss** [comment]
Das scheint ein Fehler der Steuerung selber zu sein. Wenn ich keinen neuen Wert bekomme, dann kann ich den auch nicht darstellen.
