### ISSUE TITLE
Eingabe Temperaturen (Wasser, RL, VL...)

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#6]
Zur besseren Übersichtlichkeit sollten Werte  wie
- VL Temp (luxtronik2.0.parameters.heating_curve_end_point)
- RL Temp.(luxtronik2.0.parameters.heating_curve_parallel_offset)
- Wasser Soll (luxtronik2.0.parameters.warmwater_temperature / luxtronik2.0.parameters.temperature_hot_water_target)
- Parallelverschiebung (luxtronik2.0.parameters.heating_temperature / returnTemperatureSetBack)
- Modus Wasser (luxtronik2.0.parameters.warmwater_operation_mode)
- Modus Heizung (luxtronik2.0.parameters.heating_operation_mode)

In ein eigenes "Verzeichnis" (Bsp. Benutzereingabe) abgelegt werden

**Comment by UncleSamSwiss** [comment]
Ich möchte die Werte in der gleichen Ordnung behalten, wie ich sie von der Luxtronik2 API bekomme. Es macht aber auf jeden Fall Sinn, die Werte zu dokumentieren. Zumindest für die Werte unter "parameters" und "values" kann ich das machen, die sind (mehr oder weniger) fix, die Werte unter den zwei anderen Ordnern kenne ich leider im Voraus auch nicht - die werden dynamisch von der Steuerung geliefert.

Schlussendlich wird jeder ja die Werte irgendwie in ein Skript nehmen oder auf eine VIS, und da spielt die Hierarchie keine Rolle mehr.

**Comment by TbsJah** [comment]
Sollte geschlossen werden
