### ISSUE TITLE
heating_curve_end_point VL nicht editierbar

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#7]
Eingabe nicht möglich für luxtronik2.0.parameters.heating_curve_end_point

**Comment by UncleSamSwiss** [comment]
Die beschreibbaren Werte kommen direkt aus der darunter liegenden Library:
https://github.com/coolchip/luxtronik2/blob/7e6dc944fbe8d739649e0826cc2d4234141adf1c/luxtronik.js#L479-L528

Wenn neue Werte beschreibbar sein sollten, müsstest du ein Issue im entsprechenden Repo eröffnen (auf Englisch): https://github.com/coolchip/luxtronik2/issues
