### ISSUE TITLE
heating_curve_parallel_offset RL nicht editierbar 

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#8]
Eingabe nicht möglich für luxtronik2.0.parameters.heating_curve_parallel_offset

**Comment by UncleSamSwiss** [comment]
Die beschreibbaren Werte kommen direkt aus der darunter liegenden Library:
https://github.com/coolchip/luxtronik2/blob/7e6dc944fbe8d739649e0826cc2d4234141adf1c/luxtronik.js#L479-L528

Wenn neue Werte beschreibbar sein sollten, müsstest du ein Issue im entsprechenden Repo eröffnen (auf Englisch): https://github.com/coolchip/luxtronik2/issues

**Comment by TbsJah** [comment]
Ist erledigt
Direkt auch mit dem entsprechenden Code direkt
https://github.com/coolchip/luxtronik2/issues/13

Ist es dir lieber dass hier die Fehler/ Verbesserungsvorschläge auch auf Englisch erstellt werden?

**Comment by UncleSamSwiss** [comment]
@TbsJah Grundsätzlich bevorzuge ich in GitHub Englisch, so können auch andere Benutzer die Issues lesen. Aber ich habe kein Problem mit Deutsch ;-)
