### ISSUE TITLE
Datenpunkt luxtronik2.0.Informationen.Anlagenstatus.Betriebszustand wird nicht aktualisiert

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#9]
luxtronik2.0.Informationen.Anlagenstatus.Betriebszustand Zeigt Wert an
Wird aber nicht gespeichert in der Tabelle
Änderungen werden nicht erkannt

![image](https://user-images.githubusercontent.com/34193151/99189073-acd5c800-275f-11eb-82ff-1a400acaf0fd.png)
![image](https://user-images.githubusercontent.com/34193151/99189209-76e51380-2760-11eb-9541-5021da9e2e34.png)

**Comment by TbsJah** [comment]
Status wie geschrieben wird nicht als Änderung erkannt
Abhilfe hat bei mir aktuell ein Skript geholfen welches leider aktuell nur per Shedule läuft

`var Zustand;

schedule("*/5 * * * * *", async function () {
    const Bmode = await this.getStateAsync('luxtronik2.0.Informationen.Anlagenstatus.Betriebszustand');
    if (Bmode == null || Bmode == undefined || Bmode.val == null) {
		Zustand = 'Leerlauf';
	} else {
        if (Bmode.val != '') {
            Zustand = Bmode.val.toString();
        } else {
            Zustand = 'Leerlauf';
        }
    }

    const BmodeUser = await this.getStateAsync('0_userdata.0.LWP.Anlagenstatus.Betriebszustand');
    if (BmodeUser == null || BmodeUser == undefined || BmodeUser.val == null) {
		setState("0_userdata.0.LWP.Anlagenstatus.Betriebszustand", 'Leerlauf', true);
	} 
    
    if (Zustand != getState("0_userdata.0.LWP.Anlagenstatus.Betriebszustand").val) {
        console.log('Betriebszustand ' + Zustand);
        setState("0_userdata.0.LWP.Anlagenstatus.Betriebszustand", Zustand, true);
    } 
});`

**Comment by UncleSamSwiss** [comment]
Wie sind deine History Einstellungen auf diesem Datenpunkt?

**Comment by TbsJah** [comment]
Ich nutze influxdb
![image](https://user-images.githubusercontent.com/34193151/100453782-dc6bc500-30bb-11eb-96b9-be2db160b7d4.png)

Könntest du bitte wenn die Anlage im Leerlauf ist als Wert --- oder einen anderen beliebigen String setzen?
Auf dem Webserver sind es 4x '-'
![image](https://user-images.githubusercontent.com/34193151/100453867-0ae9a000-30bc-11eb-95eb-07146f7df1d0.png)
